# Generated by Django 4.1.7 on 2023-04-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_award', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(),
        ),
    ]
