# Generated by Django 4.1.7 on 2023-04-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_award', '0002_movie_winner_alter_movie_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
